#!/usr/bin/env python3
"""Unit tests for output files generated by pbandai_scraper_v2.py.

Run with:
    pytest test_pbandai_outputs.py          # or
    python3  test_pbandai_outputs.py -v
"""

import csv
import json
import os
import re
import sys
import unittest

# Directory where the output files live
OUTPUT_DIR = os.path.dirname(os.path.abspath(__file__))

CSV_FILE = os.path.join(OUTPUT_DIR, "pbandai_products.csv")
JSON_FILE = os.path.join(OUTPUT_DIR, "pbandai_products.json")
XLSX_FILE = os.path.join(OUTPUT_DIR, "pbandai_products.xlsx")

# Regex for CJK Unified Ideographs range
CJK_RE = re.compile(r"[\u3000-\u9fff]")

EXPECTED_CSV_HEADERS = ["name", "tc_name", "price", "status", "url"]
HK_URL_PREFIX = "https://p-bandai.com/hk/"
HKD_PRICE_RE = re.compile(r"^HK\$ *\d+(?:,\d{3})*(?:\.\d{2})?$")


class TestOutputExistence(unittest.TestCase):
    """Test that all three output files exist."""

    def test_csv_exists(self):
        self.assertTrue(os.path.isfile(CSV_FILE), f"CSV file not found: {CSV_FILE}")

    def test_json_exists(self):
        self.assertTrue(os.path.isfile(JSON_FILE), f"JSON file not found: {JSON_FILE}")

    def test_xlsx_exists(self):
        self.assertTrue(os.path.isfile(XLSX_FILE), f"XLSX file not found: {XLSX_FILE}")


class TestCSVOutput(unittest.TestCase):
    """Validate the CSV output file structure and content."""

    @classmethod
    def setUpClass(cls):
        with open(CSV_FILE, encoding="utf-8-sig") as f:
            cls.reader = list(csv.DictReader(f))
        cls.rows = cls.reader

    def test_csv_is_populated(self):
        self.assertGreater(len(self.rows), 0, "CSV is empty")

    def test_csv_headers(self):
        self.assertEqual(list(self.rows[0].keys()), EXPECTED_CSV_HEADERS)

    def test_csv_no_empty_names(self):
        for i, r in enumerate(self.rows, 1):
            self.assertTrue(r["name"], f"Row {i}: empty name")

    def test_csv_no_empty_urls(self):
        for i, r in enumerate(self.rows, 1):
            self.assertTrue(r["url"], f"Row {i}: empty URL")

    def test_csv_no_empty_prices(self):
        for i, r in enumerate(self.rows, 1):
            self.assertNotEqual(
                r["price"].strip(), "N/A",
                f"Row {i}: N/A price — {r['name'][:50]}",
            )

    def test_csv_url_format(self):
        for i, r in enumerate(self.rows, 1):
            self.assertTrue(
                r["url"].startswith(HK_URL_PREFIX),
                f"Row {i}: URL does not start with {HK_URL_PREFIX}: {r['url']}",
            )

    def test_csv_price_format(self):
        for i, r in enumerate(self.rows, 1):
            with self.subTest(row=i, name=r["name"][:50]):
                # Price is optional; skip empty prices
                if not r["price"].strip():
                    continue
                # Must contain a parsable number
                price_clean = (
                    r["price"]
                    .replace("HK$", "")
                    .replace("HK", "")
                    .replace(",", "")
                    .replace(" ", "")
                )
                self.assertTrue(
                    price_clean.replace(".", "").isdigit(),
                    f"Price not numeric: {r['price']}",
                )

    def test_csv_tc_name_present(self):
        for i, r in enumerate(self.rows, 1):
            self.assertIn("tc_name", r, f"Row {i}: missing tc_name field")

    def test_csv_tc_translation(self):
        """Non-delivery-suffix names should be translated (contain CJK)."""
        untranslated = []
        for i, r in enumerate(self.rows, 1):
            if r["tc_name"] == r["name"] and "發送" not in r["name"]:
                untranslated.append((i, r["name"][:50]))
        self.assertEqual(
            len(untranslated), 0,
            f"Untranslated names: {untranslated}",
        )

    def test_csv_unique_names(self):
        names = [r["name"] for r in self.rows]
        self.assertEqual(len(names), len(set(names)))

    def test_csv_encoding(self):
        """UTF-8-BOM encoded CSV should contain Chinese characters."""
        with open(CSV_FILE, "rb") as f:
            raw = f.read(4)
        self.assertTrue(raw.startswith(b"\xef\xbb\xbf"), "Missing UTF-8 BOM")
        self.assertTrue(CJK_RE.search("".join(r["tc_name"] for r in self.rows)),
                        "No Chinese characters found in tc_name column")


class TestJSONOutput(unittest.TestCase):
    """Validate the JSON output file."""

    @classmethod
    def setUpClass(cls):
        with open(JSON_FILE, encoding="utf-8") as f:
            cls.data = json.load(f)

    def test_json_is_list(self):
        self.assertIsInstance(self.data, list)

    def test_json_is_populated(self):
        self.assertGreater(len(self.data), 0)

    def test_json_item_keys(self):
        expected = {"name", "tc_name", "price", "status", "url"}
        for i, item in enumerate(self.data):
            with self.subTest(item=i):
                self.assertEqual(set(item.keys()), expected)

    def test_json_tc_translation(self):
        untranslated = []
        for i, p in enumerate(self.data, 1):
            if p["tc_name"] == p["name"] and "發送" not in p["name"]:
                untranslated.append((i, p["name"][:50]))
        self.assertEqual(len(untranslated), 0, f"Untranslated: {untranslated}")


class TestXLSXOutput(unittest.TestCase):
    """Validate the XLSX output file (openpyxl required)."""

    @classmethod
    def setUpClass(cls):
        try:
            import openpyxl
        except ImportError:
            raise unittest.SkipTest("openpyxl not installed")
        cls.wb = openpyxl.load_workbook(XLSX_FILE, data_only=True)
        cls.ws = cls.wb.active

    def test_xlsx_has_data(self):
        self.assertGreater(self.ws.max_row, 1)

    def test_xlsx_headers(self):
        headers = [self.ws.cell(row=1, column=c).value for c in range(1, 7)]
        self.assertEqual(
            headers,
            ["#", "Product Name", "TC Product Name", "Price (HKD)", "Status", "URL"],
        )

    def test_xlsx_price_is_numeric(self):
        for row in self.ws.iter_rows(min_row=2, max_col=4, values_only=True):
            with self.subTest(name=row[1]):
                price = row[3]
                self.assertIsInstance(price, (int, float), f"Non-numeric price: {price}")

    def test_xlsx_tc_translation(self):
        untranslated = []
        for row in self.ws.iter_rows(min_row=2, values_only=True):
            name, tc = row[1], row[2]
            if tc == name and "發送" not in (name or ""):
                untranslated.append(name[:50] if name else "?")
        self.assertEqual(len(untranslated), 0, f"Untranslated: {untranslated}")


if __name__ == "__main__":
    unittest.main(verbosity=2)